name: lint-and-test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        node: ['10', '12', '14']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol native
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm test
